tamago-finance/tamago-finance

contractV1/contracts/PriceResolver.sol
contractV1/contracts/feeders/ChainlinkPriceFeeder.sol
contractV1/test/LeveragedTokenManager.js
contractV1/test/PriceResolver.js

* Call dump() to record its price
* Inherit the average price to the reference price

feat : Use 120-day average price as the reference price

---

contractV1/contracts/LeveragedTokenManager.sol
contractV1/test/LeveragedTokenManager.js

* Able to redeem collateral back
* Correct amount of collateral to be deposited

feat: redeeming index tokens

---

contractV1/contracts/ExchangeCore.sol
contractV1/contracts/ExchangePair.sol
contractV1/contracts/LeveragedTokenManager.sol
contractV1/contracts/interfaces/IExchangeCore.sol
contractV1/contracts/interfaces/IExchangePair.sol
contractV1/contracts/interfaces/ILeverageSize.sol
contractV1/test/ChainlinkPriceFeeder.js
contractV1/test/ExchangeCore.js
contractV1/test/ExchangePair.js
contractV1/test/LeveragedTokenManager.js
contractV1/test/Pmm.js

* Obsolete AMM/PMM scheme to avoid the slippage.
* Propose the shared liquidity scheme with fixed conversion rate being fetched from the Oracle.
* Minor bug fixes

Feat: Obsolete AMM/PMM

---

contractV1/contracts/ExchangeCore.sol
contractV1/contracts/ExchangePair.sol
contractV1/contracts/LeveragedTokenManager.sol

* Replace all transfer functions with safeTransfer

Fix: Use SafeERC20

---

contractV1/migrations/2_deploy_contracts.js

* Add a migration script for a new liquidity scheme

Feat: Add a migration script from 21/7/2021

---

contractV1/contracts/ExchangeCore.sol
contractV1/contracts/LeveragedTokenManager.sol
contractV1/contracts/PriceResolver.sol

Refactor: Add a leverage size interface

---

contractV1/contracts/ExchangeCore.sol
contractV1/contracts/LeveragedTokenManager.sol
contractV1/contracts/PriceResolver.sol
contractV1/contracts/interfaces/ILeverageSize.sol
contractV1/migrations/2_deploy_contracts.js
contractV1/test/ExchangeCore.js
contractV1/test/PriceResolver.js

Feat : Leverage 0.5x

---

contractV1/contracts/LeveragedTokenManager.sol
contractV1/test/LeveragedTokenManager.js

* Capped max collateral at 50,000 units (or 50,000 DAI on Mainnet) per pairs

Feat : Capped max collateral at 50,000 units

---

contractV2/contracts/TokenManager.sol
contractV2/contracts/interfaces/IToken.sol
contractV2/contracts/interfaces/ITokenManager.sol
contractV2/test/PriceResolver.js
contractV2/test/TokenManager.js

Implement a minter contract where the user can do mint, deposit, redeem of synthetic assets with two types of collateral assets.

Add Minter contract

---

contractV2/contracts/TokenManager.sol
contractV2/test/Integrations/JpyCurrency.js
contractV2/test/Integrations/TeslaStock.js
contractV2/test/PriceFeeder.js
contractV2/test/TokenManager.js

- Add integration tests for Tesla Stock, JPY Currency, the tests would need the forked mainnet url to be set.
- Fix a subtraction error

feat /fix: add integration tests for minter contract 

---

contractV2/contracts/TokenManager.sol
contractV2/test/Liquidation.js

* Allow liquidator to liquidates any under-collateralized position
* Burn synthetic tokens in return of collateral tokens + liquidation incentives

Under-collateralized positions can be liquidate

---

contractV2/contracts/Reward.sol
contractV2/test/Reward.js
contractV2/test/Reward2.js

* Admin can deposit and withdraw rewards from the contract to ensure APR is on track
* And update params

feat : add utlity functions for admin

---

contractV2/test/Reward2.js

+1 case for the reward contract.

More tests on Reward Contact

---

contractV2/contracts/TokenManager.sol
contractV2/test/TokenManager.js

Add setter for price resolver contract that allows only whitelisted users to update it.

Setter for PriceResolver contract

---

contracts/NFTManager.sol
test/NFTManager.js

* Cut redeem fees from the redeemer

Cut redeem fees

---

contracts/NFTManager.sol
contracts/utility/SyntheticNFT.sol

Follow instruction as in:
https://github.com/ProjectOpenSea/meta-transactions/blob/main/contracts/ERC1155MetaTransactionMaticSample.sol
https://docs.opensea.io/docs/polygon-basic-integration

Support Polygon's Opensea and Meta-transaction

---

contracts/NFTManager.sol
test/NFTManager.js
test/NFTManagerFullDeployment.js

* The user must provides min/max amounts when mint/redeem synthetic NFT to avoid further miscalculation in the contract

Provides Min/Max amounts when Mint/Redeem

---

contracts/mocks/MockERC20.sol
test/Helpers/index.js
test/NFTManagerFullDeployment.js

* Update test cases to use WMATIC/USDC LP instead of USDC/TAMG

Use WMATIC/USDC LP

---

contracts/Factory.sol
contracts/Registry.sol
contracts/interfaces/IRegistry.sol
test/NFTLuckbox/Factory.js
test/Registry.js

* Implement a registry contract to keep track all contracts in the system

Registry contract

---

contracts/NFTSwapPair.sol
test/NFTSwap.js

* The owner of the contract (or the gateway contract for more percise) can perform a direct swap to a specific NFT, unlike a traditional swap that the receiving NFT will be randomized.

Swap to a specific NFT

---

contracts/NFTSwapPair.sol
test/NFTSwap.js

This PR implements the lock and release mechanism that requires:
**Minter (LP provider)**
- Must lock the settlement NFT until there is a trader executes a swap function in FIFO order
**Trader**
- Must lock the settlement NFT until there is a minter executes a burn function in FIFO order

Lock and Release Mechanism

---

contracts/Factory.sol
contracts/NFTLuckBox.sol
package.json
test/NFTLuckbox/Factory.js
test/NFTLuckbox/LuckBox.js

* Cleanup Luckbox contract for v2 implementation
* POAP, Event structs
* Allows whitelist validation via off-chain merkle tree

Luckbox V2 /w Merkle Tree's whitelist

---

contracts/NFTLuckBox.sol
test/NFTLuckbox/LuckBox.js

* Implement a function allows valid users to claim POAPs
* The off-chain proof must be generated and attached (only root) to the contract before execution

[Luckbox] Claim POAPs

---

contracts/NFTLuckBox.sol

* Allows Admin users to manages the contract as opposed to only contract's owner.
* Add comments

[Luckbox] Allows Admin users to manages the contract

---

contracts/NFTLuckBoxUpgradeable.sol

convert some public functions to external functions to reduce gas cost

 perf: gas optimization

---

contracts/NFTLuckBoxUpgradeable.sol

* Allows register POAPs in batch to reduce the gas cost.

Register POAPs in batch

---

contracts/NFTMarketplace.sol
test/NFTMarketplace.js

* Implement swap fees when the buyer swaps with ERC-20 with default fees of 1%

Implement swap fees on ERC-20

---

contracts/NFTLuckboxV2.sol
test/NFTLuckboxV2.js

* Remove the deposit process to increase UX

Remove Deposit Process

---

contracts/Gateway.sol
contracts/Marketplace.sol
contracts/interfaces/IGateway.sol
contracts/mocks/MockERC1155.sol
contracts/mocks/MockERC20.sol
contracts/mocks/MockERC721.sol
test/Gateway.js
test/Helpers/index.js
test/Marketplace.js

- No longer deposit the NFT when selling
- Support Solidity 0.8
- Allows batch selling / buying

Marketplace v.2.1

---

contracts/Eligibility.sol
contracts/Marketplace.sol

Missing Setter

---

contracts/Marketplace.sol
contracts/MultiMarketplace.sol
test/Marketplace.js
test/MultiMarketplace.js

* Add the single-chain marketplace.
* Use IPFS's CID instead of in-house generated ID.

Single Chain Marketplace
